server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    
#  as a client it should not register and client cant fetch eureka details
  client:
    register-with-eureka: false
    fetch-registry: false