server:
  port: 8761

# spring:
#   security:
#     user:
#       name: nitin
#       password: nitin
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true


#  as a client it should not register and client cant fetch eureka details
  client:
    register-with-eureka: false
    fetch-registry: false
    # service-url:
    #    defaultZone : http://localhost:8761/eureka/








